export const city = [
    {
        name:'barcelona',
        code:'bar',
        ref:[{
            code:"lech",
            value:1.5
        },
        {
            code:"plc",
            value:1.5
        },
        {
            code:"guan",
            value:3
        },
        {
            code:"bar",
            value:0
        },
    ]
    },
    {
        name:'Puerto la cruz',
        code:'plc',
        ref:[{
            code:"lech",
            value:1.5
        },
        {
            code:"bar",
            value:1.5
        },
        {
            code:"guan",
            value:3
        },
        {
            code:"plc",
            value:0
        },
    ],
    },
    {
        name:'lecherias',
        code:'lech',
        ref:[{
            code:"bar",
            value:1.5
        },
        {
            code:"plc",
            value:1.5
        },
        {
            code:"guan",
            value:3
        },
        {
            code:"lech",
            value:0
        },
    ]
    },
    {
        name:'guanta',
        code:'guan',
        ref:[{
            code:"lech",
            value:3
        },
        {
            code:"plc",
            value:3
        },
        {
            code:"bar",
            value:3
        },
        {
            code:"guan",
            value:0
        },
    ]
    }
]