export const city = [
    {
        name:'barcelona',
        code:'bar',
        ref:[{
            code:"lech",
            value:2
        },
        {
            code:"plc",
            value:4
        },
        {
            code:"guan",
            value:6
        },
        {
            code:"bar",
            value:0
        },
        {
          code:"jo",
          value:14
      },
    ]
    },
    {
        name:'Pto la cruz',
        code:'plc',
        ref:[{
            code:"lech",
            value:2
        },
        {
            code:"bar",
            value:4
        },
        {
            code:"guan",
            value:2
        },
        {
            code:"plc",
            value:0
        },
        {
          code:"jo",
          value:18
      },
    ],
    },
    {
        name:'lecheria',
        code:'lech',
        ref:[{
            code:"bar",
            value:2
        },
        {
            code:"plc",
            value:2
        },
        {
            code:"guan",
            value:4
        },
        {
            code:"lech",
            value:0
        },
        {
          code:"jo",
          value:16
      },
    ]
    },
    {
        name:'guanta',
        code:'guan',
        ref:[{
            code:"lech",
            value:4
        },
        {
            code:"plc",
            value:2
        },
        {
            code:"bar",
            value:60
        },
        {
            code:"guan",
            value:0
        },
        {
          code:"jo",
          value:20
      },
    ]
    },
    {
      name:'Jose',
      code:'jo',
      ref:[{
          code:"lech",
          value:16
      },
      {
          code:"plc",
          value:18
      },
      {
          code:"bar",
          value:14
      },
      {
          code:"guan",
          value:20
      },
      {
        code:"jo",
        value:0
    },
  ]
  }
]
